djangoCgm/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

# from django.conf.urls import url
from django.urls import path, include, re_path
from django.urls import re_path as url 

from django.conf.urls import ( handler404, handler500)
from django.conf import settings
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from web.views import *
from usuarios.views import *

admin.autodiscover()
urlpatterns = [
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
	path('admin/',admin.site.urls ),
	path('',include('web.urls')),
    path('',include('usuarios.urls')),

] 

web/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('' , home.as_view(), name = 'home'),
    path('historia' , historia.as_view(), name = 'historia'),
    path('noticia/<slug:slug>/' , noticia.as_view(), name = 'noticia'),
<<<<<<< HEAD
    path('noticias', principal_noticias.as_view(), name = 'noticias'),
    path('torneos', torneos.as_view(), name= 'torneos'),
=======
    path('noticias', principal_noticias.as_view(), name = 'principal_noticias'),
    path('torneos', torneo.as_view(), name= 'torneo'),
>>>>>>> origin/master

    path('ranking', ranking.as_view(), name= 'ranking'),
    path('404', notFound404.as_view(), name= '404'),

    path('comite', comite.as_view(), name="comite"),
    path('directorio', directorio.as_view(), name='directorio'),
    path('normas_reglas', normas_reglas.as_view(), name='normas_reglas'),
    path('cuotas', cuotas.as_view(), name='cuotas'),
    path('resumen_torneo', torneo_resumen.as_view(), name='torneo_resumen'),

    #path('generar_cuotas/<int:año>/<int:valor>', generar_cuotas, name='generar_cuotas'),
    path('generar_cuotas/', generar_cuotas, name='generar_cuotas'),
    path('generar_cuotas_form/', generar_cuotas_form, name='generar_cuotas_socio'),
    path('generar_cuotas_socio/', generar_cuotas_socio, name='generar_cuotas_socio'),
    path('borrar_cuotas/', borrar_cuotas, name='borrar_cuotas'),
    path('borrar_cuotas_socio/', borrar_cuotas_socio, name='borrar_cuotas_socio'),
]

web/models.py
# from django.db import models

# Create your models here.

from django.db import models
from django.contrib import admin
from search_admin_autocomplete.admin import SearchAutoCompleteAdmin
from autoslug import AutoSlugField
from django.utils import timezone
import uuid

from .choices import *


# Create your models here.


# PLANTILLA PARA A GALERIA EN HOME
class Galeria(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titulo = models.CharField(max_length=200, blank=False, null=False)
    img = models.ImageField(upload_to="galeria/")
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Galeria"
        verbose_name_plural = "Galerias"
        ordering = ["order"]

    def __str__(self):
        return self.titulo


class GaleriaAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["titulo"]
    list_display = ("titulo", "order")
    list_per_page = 10  # No of records per page


# PLANTILLA PARA LOS LINKS EN HOME
class Links(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titulo = models.CharField(max_length=200, blank=False, null=False)
    parrafo = models.TextField()
    img = models.ImageField(upload_to="links/")
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Link"
        verbose_name_plural = "Links"
        ordering = ["order"]

    def __str__(self):
        return self.titulo


class LinksAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["titulo"]
    list_display = ("titulo", "order")
    list_per_page = 10  # No of records per page


# CONTENIDO PRINCIPAL DE HISTORIA, ETC
class Front(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    img = models.ImageField(upload_to="front/")
    titulo = models.CharField(max_length=200, blank=True, null=True)
    contenido = models.TextField(blank=True, null=True)
    order = models.IntegerField(default=0)
    file = models.FileField(upload_to="front/files/", max_length=254, blank=True)

    class Meta:
        verbose_name = "Front"
        verbose_name_plural = "Fronts"
        ordering = ["order"]

    def __str__(self):
        return self.titulo


class FrontAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["titulo"]
    list_display = ("titulo", "order")
    list_per_page = 10


# NOTICIAS DEL SITIO

class Noticia (models.Model):
    id              = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titulo          = models.CharField(max_length = 200, blank = False, null = False)
    img             = models.ImageField(upload_to='noticias/')
    fecha           = models.DateField()
    resumen         = models.CharField(max_length = 200, blank = False, null = False)
    info            = models.TextField()
    slug            = AutoSlugField(populate_from='titulo')
    is_active       = models.BooleanField('Activo',default = False)
    is_aprobado     = models.BooleanField('Aprobado',default = False)
    is_pendiente    = models.BooleanField('Pendiente',default = True)
    img1            = models.ImageField(upload_to='noticias/',blank = True)
    img2            = models.ImageField(upload_to='noticias/',blank = True)
    img3            = models.ImageField(upload_to='noticias/',blank = True)
    img4            = models.ImageField(upload_to='noticias/',blank = True)
    img5            = models.ImageField(upload_to='noticias/',blank = True)
    direccion       = models.CharField(max_length = 200, blank = True, null = False)
    region          = models.CharField(max_length=50,choices= regiones, default= 'XIII', verbose_name="Region")
 
    comentario      = models.TextField(default='Sin comentario')

    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"
        ordering = ["-fecha"]

    def __str__(self):
        return self.titulo


class NoticiaAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["titulo"]
    list_display = ("titulo", "fecha", "resumen")
    list_per_page = 10  # No of records per page


# CLASIFICA A QUE PERTENECEN LAS LISTAS DE IMAGENES DEL MODELO 'LISTA'
class Tipo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo = models.CharField(
        max_length=200, blank=False, null=False, verbose_name="Tipo"
    )
    descripcion = models.TextField()
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Tipo"
        verbose_name_plural = "Tipos"
        ordering = ["order"]

    def __str__(self):
        return str(self.tipo)


class TiposAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["tipo"]
    list_display = ("tipo", "order")
    list_per_page = 10


# ADMINISTRA EL LISTADO DE IMAGENES DE PRESIDENTES, COMITE, ETC...
class Listado (models.Model):
    id              = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo            = models.ForeignKey(Tipo, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Tipo')
    titulo          = models.CharField(max_length=200, blank= False, null = False)
    img             = models.ImageField(upload_to='listado/')
    order           = models.IntegerField(default=0)
    actual          = models.BooleanField(default= False)


    class Meta:
        verbose_name = "Listado"
        verbose_name_plural = "Listados"
        ordering = ["tipo", "order"]

    def __str__(self):
        return self.titulo


class ListadosAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):

    search_fields   = ['titulo']
    list_display    =('titulo', 'order', 'tipo', 'actual')
    list_per_page   = 10 # No of records per page


# ADMINISTRA LOS CARDS DE TORNEO
class Torneo (models.Model):
    id              = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titulo          = models.CharField(max_length=200, blank=False, null= False, verbose_name="Titulo")
    direccion       = models.CharField(max_length=200, blank=False, null= False, verbose_name="Direccion")
    region          = models.CharField(max_length=50,choices= regiones, default= 'XIII', verbose_name="Region")
    descripcion     = models.TextField(blank=True)
    img             = models.ImageField(upload_to='torneo/')
    fecha           = models.DateField()
    cupos           = models.IntegerField()
    inscritos       = models.IntegerField(default=0)
    activo          = models.BooleanField(default=True)
    proximo         = models.BooleanField(default=False)
    order           = models.IntegerField(default=0)

    class Meta:
        verbose_name    = 'Torneo'
        verbose_name_plural = 'Torneos'
        ordering    = ['-proximo','activo','fecha']

class TorneoAdmin (SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields   = ['titulo']
    list_display    = ('titulo','fecha','region','activo','proximo')
    list_per_page   = 10 # No of records per page


# ADMINISTRA LOS CARDS DE TORNEO
class Card(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    titulo = models.CharField(
        max_length=200, blank=False, null=False, verbose_name="Titulo"
    )
    direccion = models.CharField(
        max_length=200, blank=False, null=False, verbose_name="Direccion"
    )
    comuna = models.CharField(
        max_length=200, blank=False, null=False, verbose_name="Comuna"
    )
    region = models.CharField(
        max_length=50, blank=False, null=False, verbose_name="Region"
    )
    descripcion = models.TextField()
    img = models.ImageField(upload_to="cards/")
    fecha = models.DateField()
    cupos = models.IntegerField()
    inscritos = models.IntegerField(default=0)
    activo = models.BooleanField(default=False)
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Card"
        verbose_name_plural = "Cards"
        ordering = ["order"]

    def __str__(self):
        return self.titulo

class CardsAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["titulo"]
    list_display = ("titulo", "order")
    list_per_page = 10  # No of records per page


# PERFILES DE USUARIO (SOCIO, INVITADO, CAPITAN, ...)
class Perfil(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    perfil = models.CharField(
        max_length=30, blank=False, null=False, verbose_name="Perfil de usuario"
    )
    descripcion = models.TextField(
        blank=True, null=True, verbose_name="Descripcion del perfil"
    )
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Perfil"
        verbose_name_plural = "Perfiles"
        ordering = ["order"]

    def __str__(self):
        return self.perfil


class PerfilesAdmin(SearchAutoCompleteAdmin, admin.ModelAdmin):
    search_fields = ["perfil"]
    list_display = ("perfil", "order")
    list_per_page = 10


# LA ESTRUCTURA DEL USUARIO QUE INTERACTUA CON EL SITIO CGM
class Usuario(models.Model):
    id                      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rut                     = models.CharField(max_length=10, blank=False, null=False, verbose_name="Rut")
    primer_nombre           = models.CharField(max_length=200, blank=False, null=False, verbose_name="Primer nombre")
    segundo_nombre          = models.CharField(max_length=200, blank=False, null=False, verbose_name="Segundo nombre")
    apellido_paterno        = models.CharField(max_length=200, blank=False, null=False, verbose_name="Apellido paterno")
    apellido_materno        = models.CharField(max_length=200, blank=False, null=False, verbose_name="Apellido materno")
    fecha_nacimiento        = models.DateField(blank=False, null=False, verbose_name="Fecha de nacimiento")

web/templates/cards/card_noticia.html
{% load static %} {% static "" as baseUrl %}

 <div class="container ">
   <h1 class=" ">NOTICIAS</h1>
   <div class="row row-cols-1 row-cols-md-3 g-4">
     {% for value in datos %}
     
     <a class="" href="{%url 'noticia' value.titulo|slugify %}">
     <div class="col-sm-12">
      
       <div class="card h-100 cardTorneo">
           
            <img src="media/{{ value.img }}" class="card-img-top" alt="...">
            <div class="card-body cardTorneo">
              <h5 class="card-title text-center"> {{ value.titulo | upper }}</h5>
              <h6> <img src="static/web/assets/logos/point.png" style="padding: 5px; text-align: left!;"> {{ value.direccion |capfirst}}, {{ value.get_region_display }}</h6>
              <p class="card-text"> {{ value.resumen |capfirst }}</p>
            </div>
            <div class="card-footer">
              <small class="text-body-secondary"> <img src="static/web/assets/logos/calendario.png" style="padding: 10px;">{{ value.fecha }}
              </small>
            </div>
            
        </div>
      </div>
      </a>
      {% endfor %}
    </div>
    <div class="d-flex justify-content-end">
        {% if datos %}
        <nav aria-label="Page navigation example">
            <div class="nav-links">
              {% if datos.has_previous %}
                  <a class="prev page-numbers" href="?page={{ datos.previous_page_number }}{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}">
                    <span aria-hidden="true">&laquo;</span>
                   </a>
                  {% if datos.previous_page_number != 1%}

                    <a class="page-numbers" href="?page=1{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}" class="btn btn-white">
                        <span class="meta-nav screen-reader-text"> 1 </span>
                       
                    </a>
                {% endif %}
                    {% if  down  %}
                    <a class="page-numbers disable" >
                      ...
                  </a>
                  {% endif %}
                  <a class="prev page-numbers" href="?page={{ datos.previous_page_number }}{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}">
                    {{ datos.previous_page_number }}
                   </a>
              
              {% endif %}

                <strong class="page-numbers current">
                    {{ datos.number }}
                </strong>


               {% if datos.has_next %}

                <a class="next page-numbers" href="?page={{ datos.next_page_number }}{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}">
                    {{ datos.next_page_number }}
                </a>
                {% if  up  %}
                  <a class="page-numbers disable" >
                    ...
                </a>
                {% endif %}

                {% if datos.next_page_number != datos.paginator.num_pages %}
                <a class="prev page-numbers" href="?page={{ datos.paginator.num_pages  }}{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}">
                  {{ datos.paginator.num_pages  }}
                 </a>

                {% endif %}
                <a class="prev page-numbers" href="?page={{ datos.next_page_number }}{% if request.GET.buscar %}&buscar={{ request.GET.buscar}}{% endif %}" >
                  <span aria-hidden="true">&raquo;</span>
                 </a>


                {% endif %}
            </div>
        </nav>
        {% endif %}
    </div>
</div><!-- /.container -->

web/templates/cards/card_torneo.html
{% load static %} {% static "" as baseUrl %}

 <div class="container ">
   <h1 class="card-title ">OTROS TORNEOS</h1>
   <div class="row row-cols-1 row-cols-md-3 g-4">
     {% for value in torneoCard %}
     <div class="col-sm-12">
       <div class="card h-100 cardTorneo">
         <img src="media/{{ value.img }}" class="card-img-top" alt="...">
              <div class="card-body cardTorneo">
                <h5 class="card-title"> {{ value.titulo | upper }} 
                  {% if value.activo %}
                  <img src="static/web/assets/logos/lockOpen.png" style="padding: 10px;">
                  {% else %}
                  <img src="static/web/assets/logos/lockClose.png" style="padding: 10px;">
                  {% endif %} 
                </h5>
                  
                <h6> <img src="static/web/assets/logos/point.png" style="padding: 5px;">{{ value.direccion |capfirst}}, {{ value.get_region_display }}</h6>
                <p class="card-text">{{ value.descripcion |capfirst }}</p>
              </div>
              <div class="card-footer">
                <small class="text-body-secondary"> <img src="static/web/assets/logos/calendario.png" style="padding: 10px;">{{ value.fecha }}
                <img src="static/web/assets/logos/user.png" style="padding-left:30px; "> {{ value.inscritos }}/{{ value.cupos }}
              </small>
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
      </div><!-- /.container -->

web/templates/cards/main_card.html
{% load static %} {% static "" as baseUrl %}

<div class="container evento">
        <!-- Three columns of text below the carousel -->
        <div class="row  ">
          <div class="col-sm-12">
            <br><br>
            {% for value in mainCard %}  
            <div class="card mb-3 " >
              <div class="row g-0">
                <div class="col-md-8">
                  <img src="media/{{ value.img }}" class="img-fluid rounded-start torneo" alt="...">
                </div>
                <!-- {{ gato.titulo|lower }} -->
                <!-- {{ mainCard.0.descripcion|upper }} -->
                <div class="col-md-4">
                  <div class="card-body">
                    <h4 class="card-title"> {{value.titulo | upper }}  </h4>
                    <h5> Próximo Torneo 
                      {% if value.activo %}
                      <img src="static/web/assets/logos/lockOpen.png" style="padding: 10px;">
                      {% else %}
                      <img src="static/web/assets/logos/lockClose.png" style="padding: 10px;">
                      {% endif %}
                    </h5>
                        

                    <h6> <img src="static/web/assets/logos/point.png" style="padding: 5px;"> {{value.direccion |capfirst}}, {{value.get_region_display }}</h6>
                    <p class="card-text">{{ value.descripcion |capfirst }}</p>
                    <small class="text-body-secondary"> <img src="static/web/assets/logos/calendario.png" style="padding: 10px;">{{value.fecha|date:"d/m/Y"}}
                    <img src="static/web/assets/logos/user.png" style="padding-left:30px; "> {{value.inscritos}}/{{value.cupos}} 
                    </small>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
       </div><!-- /.container -->